### ISSUE TITLE
confused about generate_topk in ImageFromList.py

### ISSUE THREAD

**Issue by cvbird** [MCC-WH/CSA#6]
First of all, thank you for your code and paper. When reading your source cod, I encounter a problem:
in ImageFromList.py, generate_topk seems never been invoked in any place. However, in ___getitem__, it uses sim_indices which is only initialized in generate_topk function. I am not sure whether I miss something. Any suggestion or explanation are appreciated.
Thank you.

**Comment by MCC-WH** [comment]
Thank you for your interest in our article. I apologize for the bugs in the code. It is true that ''generate_topk'' is not used in the code, I will fix the problem in the code today and I will keep you informed when I finish.

**Comment by MCC-WH** [comment]
Thank you for your interest in our paper. I apologize for the bugs in the code. It is true that ''generate_topk'' is not used in the code, I will fix the problem in the code today and I will keep you informed when I finish.

**Comment by MCC-WH** [comment]
In fact， I have refactored the code before uploading it to GitHub. Now, ``topk_indices'' and ``sim_indices''  are calculated in the initialization function, there are some bugs here.

**Comment by MCC-WH** [comment]
In fact， I have refactored the code before uploading it to GitHub. Now, "topk_indices'' and "sim_indices'' are calculated in the initialization function, there are some bugs here.

**Comment by MCC-WH** [comment]
You can re-download the current code and try. If there are still any problems, please feel free to contact me.
