### ISSUE TITLE
training issue:

### ISSUE THREAD

**Issue by vink1994** [MCC-WH/CSA#7]
I am having trouble in training the model; kindly look into it, thanks!
Not using distributed mode
Traceback (most recent call last):
File "D:\Initital_code\CSA-main\CSA-main\train.py", line 174, in
main(args=args)
File "D:\Initital_code\CSA-main\CSA-main\train.py", line 32, in main
dataset_names = list(eval(args.dataset_names))
File "", line 1, in
NameError: name 'rSfM120k' is not defined

**Comment by MCC-WH** [comment]
I have updated the code a few days ago, you can re-download and try.

**Comment by vink1994** [comment]
I tried with updated code; getting same error

**Comment by MCC-WH** [comment]
The current code works fine on my machine, you need to check out yourself.

**Comment by MCC-WH** [comment]
The current code works fine on my machine, you need to check it out yourself.
